-- ==============================================================================
-- Migration: Password Reset System & Audit Trail (Admin OTP & Email Reset)
-- Target Tables: public.user_password_resets, public.password_reset_audit_logs
-- ==============================================================================

-- 1. Table: user_password_resets
-- Stores hashed one-time passwords generated by admin for user password reset
CREATE TABLE IF NOT EXISTS public.user_password_resets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  attempts INT DEFAULT 0,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for fast query lookup & active token validation
CREATE INDEX IF NOT EXISTS idx_upr_user_active 
ON public.user_password_resets (user_id, expires_at) 
WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_upr_created_at 
ON public.user_password_resets (created_at DESC);

-- Enable Row Level Security (RLS)
-- Deny public and client access completely: Only backend service role key can access!
ALTER TABLE public.user_password_resets ENABLE ROW LEVEL SECURITY;

-- 2. Table: password_reset_audit_logs
-- Immutable audit trail for security compliance
CREATE TABLE IF NOT EXISTS public.password_reset_audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id TEXT,
  admin_username TEXT,
  target_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  target_email TEXT,
  action TEXT NOT NULL, -- 'email_link_sent', 'otp_generated', 'otp_reset_success', 'otp_failed_attempt', 'otp_burned'
  ip_address TEXT,
  user_agent TEXT,
  metadata JSONB DEFAULT '{}'::jsonb, -- e.g. { "masked_email": "k***@gmail.com" } (NEVER plain code or password)
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for audit lookup
CREATE INDEX IF NOT EXISTS idx_pral_target_user 
ON public.password_reset_audit_logs (target_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pral_created_at 
ON public.password_reset_audit_logs (created_at DESC);

-- Enable RLS for Audit Logs
ALTER TABLE public.password_reset_audit_logs ENABLE ROW LEVEL SECURITY;
